language: python

matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           
      dist: xenial

install:
  - pip install coverage
  - pip install codacy-coverage
  - pip install -r requirements.txt

script:
  - coverage run -m unittest discover tests

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
